### Generate a summary for each product category using Generative AI

In [3]:
#import Libraries
import re, json, os
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd

In [4]:
#Data Loading

DATA_PATH = "../data/processed/customer_reviews_product_clustered.csv"

df = pd.read_csv(DATA_PATH)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head(3))

Shape: (34614, 20)

Columns:
['product_name', 'asins', 'brand', 'categories', 'manufacturer', 'reviews.date', 'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating', 'reviews.title', 'reviews.text', 'clean_text', 'sentiment', 'text_length', 'asin_clean', 'valid_asin', 'product_name_clean', 'product_id', 'cluster', 'meta_category']

,product_name,asins,brand,categories,manufacturer,reviews.date,reviews.doRecommend,reviews.numHelpful,reviews.rating,reviews.title,reviews.text,clean_text,sentiment,text_length,asin_clean,valid_asin,product_name_clean,product_id,cluster,meta_category
0,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...",Amazon,2017-01-13 00:00:00+00:00,yes,0.0,5,Kindle,This product so far has not disappointed. My c...,this product so far has not disappointed. my c...,positive,143,B01AHB9CN2,True,all new fire hd 8 tablet 8 hd display wi fi 16...,ASIN_B01AHB9CN2,3,Kindle & Fire Devices – Special Offers
1,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...",Amazon,2017-01-13 00:00:00+00:00,yes,0.0,5,very fast,great for beginner or experienced person. Boug...,great for beginner or experienced person. boug...,positive,75,B01AHB9CN2,True,all new fire hd 8 tablet 8 hd display wi fi 16...,ASIN_B01AHB9CN2,3,Kindle & Fire Devices – Special Offers
2,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...",Amazon,2017-01-13 00:00:00+00:00,yes,0.0,5,Beginner tablet for our 9 year old son.,Inexpensive tablet for him to use and learn on...,inexpensive tablet for him to use and learn on...,positive,131,B01AHB9CN2,True,all new fire hd 8 tablet 8 hd display wi fi 16...,ASIN_B01AHB9CN2,3,Kindle & Fire Devices – Special Offers

In [5]:
#original categories
print("Original categories:")
print(df["meta_category"].value_counts(dropna=False))

print("\nNumber of categories:",
      df["meta_category"].nunique(dropna=True))

Original categories:
meta_category
Kindle & Fire Devices – Special Offers     18109
Echo & Smart Home Devices                  12318
Fire Kids Edition Tablets & Accessories     1696
Kindle Fire Tablets – 16GB                  1104
Echo & Kindle Fire Devices                   855
Amazon Device Accessories & Chargers         532
Name: count, dtype: int64

Number of categories: 6

In [6]:
#Save the original category permanently

# Keep the original category created by the clustering step.
df["category"] = df["meta_category"]

print(df["category"].value_counts())

category
Kindle & Fire Devices – Special Offers     18109
Echo & Smart Home Devices                  12318
Fire Kids Edition Tablets & Accessories     1696
Kindle Fire Tablets – 16GB                  1104
Echo & Kindle Fire Devices                   855
Amazon Device Accessories & Chargers         532
Name: count, dtype: int64

In [7]:
#Inspect product names before cleaning
print("Missing product names:",
      df["product_name_clean"].isna().sum())

print("\nExamples of product names:")
display(
    df["product_name_clean"]
    .dropna()
    .value_counts()
    .head(20)
)

Missing product names: 0

Examples of product names:

product_name_clean
fire tablet 7 display wi fi 8 gb includes special offers magenta                                                                                                                                           10962
unknown                                                                                                                                                                                                     6087
echo white echo white                                                                                                                                                                                       3976
amazon kindle paperwhite ebook reader 4 gb 6 monochrome paperwhite touchscreen wi fi black                                                                                                                  3176
all new fire hd 8 tablet 8 hd display wi fi 16 gb includes special offers magenta                                                                                                                           2814
amazon fire tv amazon fire tv                                                                                                                                                                               2527
fire kids edition tablet 7 display wi fi 16 gb green kid proof case                                                                                                                                         1684
brand new amazon kindle fire 16gb 7 ips display tablet wifi 16 gb blue                                                                                                                                      1033
kindle voyage e reader 6 high resolution display 300 ppi with adaptive built in light pagepress sensors wi fi includes special offers                                                                        580
fire tablet 7 display wi fi 8 gb includes special offers black                                                                                                                                               363
amazon amazon tap portable bluetooth and wi fi speaker black amazon amazon tap portable bluetooth and wi fi speaker black                                                                                    318
all new kindle e reader black 6 glare free touchscreen display wi fi includes special offers                                                                                                                 211
amazon 5w usb official oem charger and power adapter for fire tablets and kindle ereaders amazon 5w usb official oem charger and power adapter for fire tablets and kindle ereaders                          207
all new fire hd 8 tablet 8 hd display wi fi 32 gb includes special offers magenta                                                                                                                            146
amazon fire hd 8 8in tablet 16gb black b018szt3bk 6th gen 2016 android amazon fire hd 8 8in tablet 16gb black b018szt3bk 6th gen 2016 android                                                                135
amazon fire hd 10 tablet wi fi 16 gb special offers silver aluminum amazon fire hd 10 tablet wi fi 16 gb special offers silver aluminum                                                                      128
kindle oasis e reader with leather charging cover merlot 6 high resolution display 300 ppi wi fi includes special offers                                                                                      67
amazon 9w powerfast official oem usb charger and power adapter for fire tablets and kindle ereaders amazon 9w powerfast official oem usb charger and power adapter for fire tablets and kindle ereaders       36
kindle paperwhite e reader white 6 high resolution display 300 ppi with built in light wi fi includes special offers                                                                                          30
amazon kindle voyage 4gb wi fi 3g black amazon kindle voyage 4gb wi fi 3g black                                                                                                                               25
Name: count, dtype: int64

In [8]:
#Clean duplicate product names

def dedupe_halves(s):
    """
    If a product name is accidentally repeated twice,
    keep only one copy.

    Example:
    A B C A B C
    becomes:
    A B C
    """
    
    words = s.split()
    half = len(words) // 2

    if (
        len(words) % 2 == 0
        and words[:half] == words[half:]
    ):
        return " ".join(words[:half])

    return s

In [9]:
#Clean product display names    
FIXES = {
    "Gb": "GB",
    "Hd": "HD",
    "Ppi": "ppi",
    "Tv": "TV",
    "Usb": "USB",
    "Oem": "OEM",
    "Wi Fi": "Wi-Fi",
    "6Th": "6th",
    "5Th": "5th",
    "4Th": "4th",
    "3Rd": "3rd",
    "2Nd": "2nd",
}


def display_name(s):
    """
    Makes a product name easier to read.

    This function changes presentation only.
    It does NOT decide which category the product belongs to.
    """

    if not isinstance(s, str):
        return s

    # Remove accidental duplicated half
    s = dedupe_halves(s)

    # Remove ASIN-like codes
    words = [
        w for w in s.split()
        if not re.fullmatch(r"b0[0-9a-z]{8}", w.lower())
    ]

    # Title case
    out = " ".join(words).title()

    # Restore important technical abbreviations
    for old, new in FIXES.items():
        out = re.sub(
            rf"\b{re.escape(old)}\b",
            new,
            out
        )

    # Formatting fixes
    out = re.sub(r"(\d+)Gb\b", r"\1 GB", out)
    out = re.sub(r"(\d+)In\b", r"\1-inch", out)

    return out

In [10]:
#Create the usable product label
name = df["product_name_clean"]

# Treat only genuinely missing/empty/unknown names as unusable.
unknown = (
    name.isna()
    | name.astype(str).str.strip().str.lower().isin(
        ["", "unknown", "missing", "nan"]
    )
)

df["product_label"] = name.where(~unknown, np.nan)

# Clean duplicated product names
df["product_label"] = df["product_label"].map(
    lambda x: dedupe_halves(x) if isinstance(x, str) else x
)

print("Reviews without usable product name:",
      df["product_label"].isna().sum())

print("Distinct usable product names:",
      df["product_label"].nunique())

Reviews without usable product name: 6087
Distinct usable product names: 47

In [11]:
#Check all six categories again
category_summary = (
    df.groupby("category")
      .agg(
          reviews=("reviews.rating", "size"),
          products=("product_label", "nunique")
      )
      .sort_values("reviews", ascending=False)
)

display(category_summary)

                                         reviews  products
category
Kindle & Fire Devices – Special Offers     18109        26
Echo & Smart Home Devices                  12318        16
Fire Kids Edition Tablets & Accessories     1696         5
Kindle Fire Tablets – 16GB                  1104         3
Echo & Kindle Fire Devices                   855         3
Amazon Device Accessories & Chargers         532         3

In [12]:
#Inspect products inside each category

for category, group in df.groupby("category"):

    product_counts = (
        group["product_label"]
        .dropna()
        .value_counts()
    )

    print("\n" + "=" * 80)
    print(category)
    print("=" * 80)

    print("Total reviews:", len(group))
    print("Usable products:", len(product_counts))

    print("\nTop products:")
    
    for product, count in product_counts.head(10).items():
        print(f"{count:>6}  {display_name(product)}")

================================================================================
Amazon Device Accessories & Chargers
================================================================================
Total reviews: 532
Usable products: 3

Top products:
   211  All New Kindle E Reader Black 6 Glare Free Touchscreen Display Wi-Fi Includes Special Offers
   188  Amazon 5W USB Official OEM Charger And Power Adapter For Fire Tablets And Kindle Ereaders
     1  Amazon Kindle Fire HD 3rd Generation 8 GB

================================================================================
Echo & Kindle Fire Devices
================================================================================
Total reviews: 855
Usable products: 3

Top products:
   387  Echo White
   211  Fire Tablet 7 Display Wi-Fi 8 GB Includes Special Offers Magenta
     1  Amazon Kindle Fire HD 3rd Generation 8 GB

================================================================================
Echo & Smart Home Devices
================================================================================
Total reviews: 12318
Usable products: 16

Top products:
  3569  Echo White
  2527  Amazon Fire TV
   318  Amazon Amazon Tap Portable Bluetooth And Wi-Fi Speaker Black
   128  Amazon Fire HD 10 Tablet Wi-Fi 16 GB Special Offers Silver Aluminum
    36  Amazon 9W Powerfast Official OEM USB Charger And Power Adapter For Fire Tablets And Kindle Ereaders
     9  Kindle Dx Leather Cover Black Fits 9 7 Display Latest And 2nd Generation Kindle Dxs
     7  Amazon 5W USB Official OEM Charger And Power Adapter For Fire Tablets And Kindle Ereaders
     7  New Amazon Kindle Fire HD 9W Powerfast Adapter Charger Micro USB Angle Cable
     6  Amazon Fire HD 6 Standing Protective Case 4th Generation 2014 Release Cayenne Red
     4  Amazon Kindle Fire 5Ft USB To Micro USB Cable Works With Most Micro USB Tablets

================================================================================
Fire Kids Edition Tablets & Accessories
================================================================================
Total reviews: 1696
Usable products: 5

Top products:
  1443  Fire Kids Edition Tablet 7 Display Wi-Fi 16 GB Green Kid Proof Case
   248  Amazon Kindle Paperwhite Ebook Reader 4 GB 6 Monochrome Paperwhite Touchscreen Wi-Fi Black
     2  Amazon Kindle Lighted Leather Cover
     2  Kindle Keyboard
     1  Amazon Kindle Lighted Leather Cover Kindle Keyboard

================================================================================
Kindle & Fire Devices – Special Offers
================================================================================
Total reviews: 18109
Usable products: 26

Top products:
 10751  Fire Tablet 7 Display Wi-Fi 8 GB Includes Special Offers Magenta
  2928  Amazon Kindle Paperwhite Ebook Reader 4 GB 6 Monochrome Paperwhite Touchscreen Wi-Fi Black
  2814  All New Fire HD 8 Tablet 8 HD Display Wi-Fi 16 GB Includes Special Offers Magenta
   580  Kindle Voyage E Reader 6 High Resolution Display 300 ppi With Adaptive Built In Light Pagepress Sensors Wi-Fi Includes Special Offers
   363  Fire Tablet 7 Display Wi-Fi 8 GB Includes Special Offers Black
   173  Brand New Amazon Kindle Fire 16 GB 7 Ips Display Tablet Wifi 16 GB Blue
   146  All New Fire HD 8 Tablet 8 HD Display Wi-Fi 32 GB Includes Special Offers Magenta
   135  Amazon Fire HD 8 8-inch Tablet 16 GB Black 6th Gen 2016 Android
    67  Kindle Oasis E Reader With Leather Charging Cover Merlot 6 High Resolution Display 300 ppi Wi-Fi Includes Special Offers
    30  Kindle Paperwhite E Reader White 6 High Resolution Display 300 ppi With Built In Light Wi-Fi Includes Special Offers

================================================================================
Kindle Fire Tablets – 16GB
================================================================================
Total reviews: 1104
Usable products: 3

Top products:
   860  Brand New Amazon Kindle Fire 16 GB 7 Ips Display Tablet Wifi 16 GB Blue
   241  Fire Kids Edition Tablet 7 Display Wi-Fi 16 GB Green Kid Proof Case
     3  Amazon Kindle Touch Leather Case 4th Generation 2011 Release Olive Green

In [13]:
#Sentiment summary

def sentiment_summary(product_df):
    """
    Calculate the percentage of positive,
    neutral and negative reviews for one product.
    """

    counts = product_df["sentiment"].value_counts()
    total = len(product_df)

    if total == 0:
        return {
            "positive_pct": 0,
            "neutral_pct": 0,
            "negative_pct": 0,
        }

    return {
        "positive_pct": round(
            counts.get("positive", 0) / total * 100,
            1
        ),
        "neutral_pct": round(
            counts.get("neutral", 0) / total * 100,
            1
        ),
        "negative_pct": round(
            counts.get("negative", 0) / total * 100,
            1
        ),
    }

In [14]:
#Select review examples
def sample_reviews(rv, low, n, max_chars=280):
    """
    Select real review examples for Claude.

    low=True:
        select 1-3 star reviews

    low=False:
        select 4-5 star reviews

    We prefer reviews with more helpful votes.
    """

    if low:
        sub = rv[
            rv["reviews.rating"] <= 3
        ].copy()

        # 1-2 star reviews first, then 3 star
        sub["_severity"] = (
            sub["reviews.rating"] > 2
        ).astype(int)

    else:
        sub = rv[
            rv["reviews.rating"] >= 4
        ].copy()

        sub["_severity"] = 0

    # Remove extremely short/long reviews
    sub = sub[
        sub["reviews.text"]
        .fillna("")
        .str.len()
        .between(40, max_chars)
    ]

    # Sort severe reviews first,
    # then helpful reviews first
    sort_columns = ["_severity"]
    ascending = [True]

    if "reviews.numHelpful" in sub.columns:
        sort_columns.append("reviews.numHelpful")
        ascending.append(False)

    sub = (
        sub
        .sort_values(
            sort_columns,
            ascending=ascending
        )
        .head(n)
    )

    return [
        f"({int(rating)} stars) {text}"
        for rating, text in zip(
            sub["reviews.rating"],
            sub["reviews.text"]
        )
    ]

In [15]:
#Create product evidence
def product_facts(product_df, label, role):
    """
    Create the factual information Claude is allowed to use
    for one product.
    """

    return {
        "name": display_name(label),

        "role": role,

        "review_count": len(product_df),

        "average_rating": round(
            product_df["reviews.rating"].mean(),
            2
        ),

        **sentiment_summary(product_df),

        "negative_reviews_1_2_stars": int(
            (product_df["reviews.rating"] <= 2).sum()
        ),

        "reviews_3_stars_or_less": int(
            (product_df["reviews.rating"] <= 3).sum()
        ),

        "sample_of_positive_reviews": sample_reviews(
            product_df,
            low=False,
            n=4
        ),

        "sample_of_low_rated_reviews": sample_reviews(
            product_df,
            low=True,
            n=10
        ),
    }

In [16]:
#Build facts for ONE category
MIN_PRODUCT_REVIEWS = 10

GLOBAL_MEAN = df["reviews.rating"].mean()


def build_facts(df, category):

    # IMPORTANT:
    # Use the ORIGINAL category.
    cat = df[
        df["category"] == category
    ]

    # Only reviews with a usable product name
    named = cat[
        cat["product_label"].notna()
    ]

    # Count reviews for each product
    product_stats = (
        named
        .groupby("product_label")
        .agg(
            n_reviews=("reviews.rating", "size"),
            avg_rating=("reviews.rating", "mean")
        )
        .reset_index()
    )

    # Keep products with at least 10 reviews
    ranked = product_stats[
        product_stats["n_reviews"] >= MIN_PRODUCT_REVIEWS
    ].copy()

    # If no products meet the threshold,
    # return a category-level result instead of deleting the category.
    if len(ranked) == 0:

        return {
            "category": category,
            "reviews_in_category": len(cat),
            "products_ranked": 0,
            "min_reviews_used": MIN_PRODUCT_REVIEWS,
            "pct_reviews_without_product_name": round(
                (1 - len(named) / len(cat)) * 100,
                1
            ),
            "most_reviewed_product": None,
            "products": [],
            "data_warning": (
                "No product has enough reviews for reliable "
                "product-level ranking."
            ),
        }

    # Bayesian-style score.
    # This prevents a product with very few reviews
    # from automatically winning just because of a high rating.
    ranked["score"] = (
        (
            ranked["n_reviews"]
            /
            (ranked["n_reviews"] + MIN_PRODUCT_REVIEWS)
        )
        * ranked["avg_rating"]
        +
        (
            MIN_PRODUCT_REVIEWS
            /
            (ranked["n_reviews"] + MIN_PRODUCT_REVIEWS)
        )
        * GLOBAL_MEAN
    )

    ranked = ranked.sort_values(
        "score",
        ascending=False
    )

    # Most reviewed product
    best_seller = (
        ranked
        .sort_values(
            "n_reviews",
            ascending=False
        )
        .iloc[0]
    )

    # Take top 3, if available
    top_products = ranked.head(3)

    # Lowest-ranked product
    # Only mark as weakest if there is more than one product.
    if len(ranked) >= 2:
        weakest_product = ranked.iloc[-1]
    else:
        weakest_product = None

    products = []

    # Add top products
    for row in top_products.itertuples():

        role = "top"

        # If this is also the weakest product,
        # don't duplicate it later.
        if (
            weakest_product is not None
            and row.product_label
            == weakest_product["product_label"]
        ):
            role = "top_and_weakest"

        product_df = named[
            named["product_label"]
            == row.product_label
        ]

        products.append(
            product_facts(
                product_df,
                row.product_label,
                role
            )
        )

    # Add weakest product if it was not already included.
    if (
        weakest_product is not None
        and weakest_product["product_label"]
        not in top_products["product_label"].values
    ):

        product_df = named[
            named["product_label"]
            == weakest_product["product_label"]
        ]

        products.append(
            product_facts(
                product_df,
                weakest_product["product_label"],
                "weakest"
            )
        )

    return {
        "category": category,

        "reviews_in_category": len(cat),

        "products_ranked": len(ranked),

        "min_reviews_used": MIN_PRODUCT_REVIEWS,

        "pct_reviews_without_product_name": round(
            (1 - len(named) / len(cat)) * 100,
            1
        ),

        "most_reviewed_product": {
            "name": display_name(
                best_seller["product_label"]
            ),
            "review_count": int(
                best_seller["n_reviews"]
            ),
            "average_rating": round(
                float(best_seller["avg_rating"]),
                2
            ),
        },

        "products": products,

        "data_warning": (
            "Some products have relatively few reviews; "
            "rankings should be interpreted cautiously."
            if (ranked["n_reviews"] < 30).any()
            else None
        ),
    }

In [17]:
#Build facts for ALL SIX categories
categories = (
    df["category"]
    .dropna()
    .unique()
    .tolist()
)

print("Categories found:", len(categories))
print(categories)

Categories found: 6
['Kindle & Fire Devices – Special Offers', 'Fire Kids Edition Tablets & Accessories', 'Amazon Device Accessories & Chargers', 'Echo & Kindle Fire Devices', 'Kindle Fire Tablets – 16GB', 'Echo & Smart Home Devices']

In [18]:
all_facts = {}

for category in categories:

    facts = build_facts(
        df,
        category
    )

    all_facts[category] = facts

print("\nCategories prepared for Claude:",
      len(all_facts))

for category, facts in all_facts.items():

    print(
        f"- {category}: "
        f"{facts['reviews_in_category']} reviews, "
        f"{facts['products_ranked']} ranked products"
    )

Categories prepared for Claude: 6
- Kindle & Fire Devices – Special Offers: 18109 reviews, 14 ranked products
- Fire Kids Edition Tablets & Accessories: 1696 reviews, 2 ranked products
- Amazon Device Accessories & Chargers: 532 reviews, 2 ranked products
- Echo & Kindle Fire Devices: 855 reviews, 2 ranked products
- Kindle Fire Tablets – 16GB: 1104 reviews, 2 ranked products
- Echo & Smart Home Devices: 12318 reviews, 5 ranked products

In [19]:
#Specifically inspect Accessories & Chargers
ACCESSORIES_CATEGORY = "Amazon Device Accessories & Chargers"

facts = all_facts.get(
    ACCESSORIES_CATEGORY
)

print(
    json.dumps(
        facts,
        indent=2,
        ensure_ascii=False
    )
)

{
  "category": "Amazon Device Accessories & Chargers",
  "reviews_in_category": 532,
  "products_ranked": 2,
  "min_reviews_used": 10,
  "pct_reviews_without_product_name": 24.8,
  "most_reviewed_product": {
    "name": "All New Kindle E Reader Black 6 Glare Free Touchscreen Display Wi-Fi Includes Special Offers",
    "review_count": 211,
    "average_rating": 4.43
  },
  "products": [
    {
      "name": "Amazon 5W USB Official OEM Charger And Power Adapter For Fire Tablets And Kindle Ereaders",
      "role": "top",
      "review_count": 188,
      "average_rating": 4.45,
      "positive_pct": 86.7,
      "neutral_pct": 2.7,
      "negative_pct": 10.6,
      "negative_reviews_1_2_stars": 20,
      "reviews_3_stars_or_less": 25,
      "sample_of_positive_reviews": [
        "(5 stars) Bought to use with Kindle. Works fine! Good quality and charges the kindle quickly.",
        "(5 stars) Works just as you'd expect. Small and compact which is nice, and charges the kindle really quickly (faster than it charges on my laptop). A little expensive for what it is, but glad I ordered this.",
        "(5 stars) So far this product has worked great. I bought it to replace my kindle charger that was no longer charging my older kindle fire. I bought a new USB cord as well. It charges my kindle so much faster than any of the other chargers I have. I would definitely recommend this product.",
        "(5 stars) Great product... Met all my expectations"
      ],
      "sample_of_low_rated_reviews": [
        "(1 stars) Most buyers will have a phone or other charger that will work so you probably don't need to buy this.",
        "(1 stars) cheap - need to constantly make sure plugged in - slightly too small - saved some bucks there - not amazon quality",
        "(1 stars) If you actually paid 20 for this adapter, you're out of your mind.",
        "(1 stars) I wish this came in white to match my Kindle Paperwhite",
        "(1 stars) Really expected a chord with it for the price we paid. Very dissapointed.",
        "(1 stars) Not compatible with South African plug standards. Bought this unnecessarily.",
        "(1 stars) It wasn't what I thought it was the price was too much for what I got Very disappointed",
        "(1 stars) I had to buy it, what else is there to say.",
        "(1 stars) 5 dollar AC to USB power adapter for 20 buck",
        "(2 stars) Q: What's the difference between a 19.99 Amazon 5W USB Official OEM Charger and Power Supply and a 5.95 5V 1A (1000mA) USB port power supply - UL ListedA: 14.04 Calling it a 5W charger rather than a 5V 1A charger is a distinction without a difference."
      ]
    },
    {
      "name": "All New Kindle E Reader Black 6 Glare Free Touchscreen Display Wi-Fi Includes Special Offers",
      "role": "top_and_weakest",
      "review_count": 211,
      "average_rating": 4.43,
      "positive_pct": 84.8,
      "neutral_pct": 7.1,
      "negative_pct": 8.1,
      "negative_reviews_1_2_stars": 17,
      "reviews_3_stars_or_less": 32,
      "sample_of_positive_reviews": [
        "(5 stars) I'm very glad that I made this purchase. I don't often bring my computer with me when I travel. I enjoy having the option of using a standard outlet to charge the Paperwhite.",
        "(4 stars) Works good but, you can purchase a charger with same or better specs. on Amazon MUCH cheaper. I purchased a 5 port 30 watt charger for about 1/2 of the cost of this.",
        "(5 stars) great - can charge Kindle e-book reader without the need of computer being on.",
        "(5 stars) So helpful to power up our readers anywhere."
      ],
      "sample_of_low_rated_reviews": [
        "(1 stars) Pretty dumb that you have to.buy a charger port",
        "(1 stars) Too expensive. Should be included, at no extra cost, with the Kindle.",
        "(1 stars) My old kindle charger works fine - that wasn't clear when I bought a new kindle white. And now you want to charge me 6.95 to send it back. Forget it!! I'll keep the extra charger",
        "(1 stars) This is honestly a little expensive. And I can find other ways to charge my devices.",
        "(1 stars) A waste of money. You don't need this. Just plug your tablet into your computer and the charge lasts for a month.",
        "(1 stars) Do not pay attention to their ad. It says the plug is not included with the kindle and it absolutely is. If they lie about this sort of thing what else do you think the lie about. Steer clear these guys are rip off artist.",
        "(1 stars) Just got home and found the packet is empty, there is no product we ordered in it. What do we do now",
        "(1 stars) feel it should have come with paperwhite kindle and that I should not have had to buy it",
        "(1 stars) Whats the point of this without the cable to charge!",
        "(2 stars) It was doing a great job charging my kindle, but now it takes almost all day to charge."
      ]
    }
  ],
  "data_warning": null
}

In [20]:
#Check every category before Claude

for category, facts in all_facts.items():

    print("\n" + "=" * 80)
    print(category)
    print("=" * 80)

    print("Reviews:",
          facts["reviews_in_category"])

    print("Ranked products:",
          facts["products_ranked"])

    print("Missing product name:",
          facts["pct_reviews_without_product_name"],
          "%")

    if facts["most_reviewed_product"]:
        print(
            "Most reviewed:",
            facts["most_reviewed_product"]["name"]
        )

    print("\nProducts:")

    for product in facts["products"]:
        print(
            f"  - {product['name']}"
            f" | {product['average_rating']} rating"
            f" | {product['review_count']} reviews"
            f" | {product['role']}"
        )

    if facts.get("data_warning"):
        print(
            "\nWARNING:",
            facts["data_warning"]
        )

================================================================================
Kindle & Fire Devices – Special Offers
================================================================================
Reviews: 18109
Ranked products: 14
Missing product name: 0.0 %
Most reviewed: Fire Tablet 7 Display Wi-Fi 8 GB Includes Special Offers Magenta

Products:
  - Amazon Kindle Paperwhite Ebook Reader 4 GB 6 Monochrome Paperwhite Touchscreen Wi-Fi Black | 4.77 rating | 2928 reviews | top
  - Fire HD 8 Tablet With Alexa 8 HD Display 32 GB Tangerine With Special Offers | 4.86 rating | 14 reviews | top
  - Kindle Voyage E Reader 6 High Resolution Display 300 ppi With Adaptive Built In Light Pagepress Sensors Wi-Fi Includes Special Offers | 4.74 rating | 580 reviews | top
  - Fire Tablet 7 Display Wi-Fi 8 GB Includes Special Offers Magenta | 4.45 rating | 10751 reviews | weakest

WARNING: Some products have relatively few reviews; rankings should be interpreted cautiously.

================================================================================
Fire Kids Edition Tablets & Accessories
================================================================================
Reviews: 1696
Ranked products: 2
Missing product name: 0.0 %
Most reviewed: Fire Kids Edition Tablet 7 Display Wi-Fi 16 GB Green Kid Proof Case

Products:
  - Amazon Kindle Paperwhite Ebook Reader 4 GB 6 Monochrome Paperwhite Touchscreen Wi-Fi Black | 4.56 rating | 248 reviews | top
  - Fire Kids Edition Tablet 7 Display Wi-Fi 16 GB Green Kid Proof Case | 4.52 rating | 1443 reviews | top_and_weakest

================================================================================
Amazon Device Accessories & Chargers
================================================================================
Reviews: 532
Ranked products: 2
Missing product name: 24.8 %
Most reviewed: All New Kindle E Reader Black 6 Glare Free Touchscreen Display Wi-Fi Includes Special Offers

Products:
  - Amazon 5W USB Official OEM Charger And Power Adapter For Fire Tablets And Kindle Ereaders | 4.45 rating | 188 reviews | top
  - All New Kindle E Reader Black 6 Glare Free Touchscreen Display Wi-Fi Includes Special Offers | 4.43 rating | 211 reviews | top_and_weakest

================================================================================
Echo & Kindle Fire Devices
================================================================================
Reviews: 855
Ranked products: 2
Missing product name: 29.9 %
Most reviewed: Echo White

Products:
  - Fire Tablet 7 Display Wi-Fi 8 GB Includes Special Offers Magenta | 4.53 rating | 211 reviews | top
  - Echo White | 4.4 rating | 387 reviews | top_and_weakest

================================================================================
Kindle Fire Tablets – 16GB
================================================================================
Reviews: 1104
Ranked products: 2
Missing product name: 0.0 %
Most reviewed: Brand New Amazon Kindle Fire 16 GB 7 Ips Display Tablet Wifi 16 GB Blue

Products:
  - Brand New Amazon Kindle Fire 16 GB 7 Ips Display Tablet Wifi 16 GB Blue | 4.54 rating | 860 reviews | top
  - Fire Kids Edition Tablet 7 Display Wi-Fi 16 GB Green Kid Proof Case | 4.47 rating | 241 reviews | top_and_weakest

================================================================================
Echo & Smart Home Devices
================================================================================
Reviews: 12318
Ranked products: 5
Missing product name: 46.3 %
Most reviewed: Echo White

Products:
  - Amazon Fire HD 10 Tablet Wi-Fi 16 GB Special Offers Silver Aluminum | 4.77 rating | 128 reviews | top
  - Amazon Amazon Tap Portable Bluetooth And Wi-Fi Speaker Black | 4.73 rating | 318 reviews | top
  - Echo White | 4.68 rating | 3569 reviews | top
  - Amazon Fire TV | 4.65 rating | 2527 reviews | weakest

In [21]:
#Save the structured evidence
REPORTS_DIR = Path("../reports")
SUMMARY_DATA_DIR = REPORTS_DIR / "summaries_data"

REPORTS_DIR.mkdir(
    exist_ok=True
)

SUMMARY_DATA_DIR.mkdir(
    exist_ok=True
)

for category, facts in all_facts.items():

    slug = re.sub(
        r"[^a-z0-9]+",
        "_",
        category.lower()
    ).strip("_")

    output_file = (
        SUMMARY_DATA_DIR
        / f"{slug}.json"
    )

    output_file.write_text(
        json.dumps(
            facts,
            indent=2,
            ensure_ascii=False
        ),
        encoding="utf-8"
    )

print(
    f"Saved evidence for {len(all_facts)} categories."
)

Saved evidence for 6 categories.

## Claude API Integration

In [37]:
#Connect to Claude
import anthropic
from dotenv import load_dotenv

load_dotenv()

api_key_found = bool(
    os.getenv("ANTHROPIC_API_KEY")
)

print(
    "API key found:",
    api_key_found
)

client = anthropic.Anthropic()

MODEL = "claude-haiku-4-5"

API key found: True

In [38]:
#Claude system prompt
SYSTEM_STRICT = """
You are a factual consumer product review analyst.

Your job is to create a short buying guide using ONLY the supplied evidence.

IMPORTANT RULES:

1. Never invent facts, specifications, prices, features or products.

2. Every rating, percentage and review count must come from the supplied data.

3. Product specifications may only be mentioned when they appear
   directly in the product name or review samples.

4. Use the positive review samples to describe praise.

5. Use the low-rated review samples to identify complaint themes.

6. When discussing complaint themes, clearly say they come from
   the sampled low-rated reviews.
   Do NOT treat the sample as the complete set of complaints.

7. Never say that a complaint appears in X% of all reviews
   unless that exact number is provided in the data.

8. Low-rated samples may contain praise or irrelevant text.
   Ignore those when identifying complaints.

9. Compare products against each other.
   A "weakest" product means lowest-ranked in this category,
   not necessarily a bad product.

10. If products have similar ratings, say that the difference is small.

11. If the evidence is thin, say so honestly.

12. Do not move products between categories.
    The supplied category is authoritative.

13. Use the product names exactly as supplied.

14. Do not claim that reviews were verified.

15. Keep recommendations consistent with the evidence.
"""

In [39]:
#Claude output format
FORMAT_STRICT = """
Write a consumer buying guide in Markdown.

Use exactly these sections:

# {category} Buying Guide

## Overview

Explain:
- what this category contains
- how many reviews are included
- how many products were ranked

Mention if the category has limited evidence.

## Top Products

Cover the top products supplied in the data.

For each product include:
- average rating
- positive percentage
- what buyers praise
- how it differs from the other products

If there are only 2 products, discuss both.
Do NOT invent a third product.

## Main Complaints

For each relevant product:
- identify the main complaint themes
- give sample counts such as "4 of the 10 sampled low-rated reviews"
- explain how common serious complaints are overall using the supplied data

Only use short direct quotes when useful.
A quote must be copied exactly from the supplied review samples
and must be no more than 12 words.

## Weakest Product

Identify the lowest-ranked product when one exists.

Explain:
- its rating
- its negative-review percentage
- its main complaint themes

If the difference is small, explicitly say that it is only relatively weaker.

## Recommendation

Give a short recommendation explaining which product
may suit which type of buyer.

Do not invent buyer characteristics that are not supported
by the supplied evidence.

Keep the guide around 300-380 words.
"""

In [41]:
#Function to send ONE category to Claude
def generate_guide(facts):

    prompt = (
        "CATEGORY EVIDENCE:\n"
        + json.dumps(
            facts,
            indent=2,
            ensure_ascii=False
        )
        + "\n\n"
        + FORMAT_STRICT.format(
            category=facts["category"]
        )
    )

    message = client.messages.create(
        model=MODEL,
        max_tokens=1400,
        system=SYSTEM_STRICT,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    if message.stop_reason == "max_tokens":
        print(
            "WARNING: Claude stopped because "
            "the maximum token limit was reached."
        )

    return message.content[0].text

In [ ]:
#Test Accessories & Chargers FIRST
test_facts = all_facts[
    "Amazon Device Accessories & Chargers"
]

test_article = generate_guide(
    test_facts
)

print(test_article)

In [42]:
#Generate all six Categories
all_summaries = {}

for category, facts in all_facts.items():

    print("\n" + "=" * 80)
    print(category)
    print("=" * 80)

    article = generate_guide(
        facts
    )

    all_summaries[category] = article

    print(article)

================================================================================
Kindle & Fire Devices – Special Offers
================================================================================
# Kindle & Fire Devices – Special Offers Buying Guide

## Overview

This category includes Kindle e-readers and Fire tablets sold with Amazon Special Offers. The guide covers 14 ranked products based on 18,109 customer reviews. Note that some products have relatively few reviews; rankings should be interpreted cautiously.

## Top Products

**Amazon Kindle Paperwhite Ebook Reader 4 GB 6 Monochrome Paperwhite Touchscreen Wi-Fi Black**
- Rating: 4.77 / 5.0 | 97.3% positive
- Buyers praise the backlit display, noting "back lighting is great" and appreciating variable lighting for reading at night. The touchscreen setup is easy, and readers highlight that it feels "like reading a piece of paper."

**Kindle Voyage E Reader 6 High Resolution Display 300 ppi With Adaptive Built In Light Pagepress Sensors Wi-Fi Includes Special Offers**
- Rating: 4.74 / 5.0 | 96.9% positive
- This model earns praise for its high-resolution display described as "one hundred percent book like." Buyers highlight the lightweight design, 3-week battery life, anti-glare screen, and easy page turns. However, at double the Paperwhite's price, some feel the upgrade isn't worth the cost.

**Fire HD 8 Tablet With Alexa 8 HD Display 32 GB Tangerine With Special Offers**
- Rating: 4.86 / 5.0 | 100% positive
- Despite limited review volume (14 reviews), this tablet scores perfectly. Buyers appreciate internet access, library book support, and value for the price.

## Main Complaints

**Kindle Paperwhite** faces significant concerns about limitations: 10 of the sampled low-rated reviews highlight inability to access library books or non-Amazon content. Multiple reviewers note "you cannot load apps" and expected internet access that wasn't available. Touch navigation frustrates some users, with one reviewer stating "navigating on it drove me nuts."

**Fire Tablet 7** shows more technical issues. Among sampled low-rated reviews, complaints include lack of Google services (YouTube, Gmail), slow browsing speeds, and app failures. Connectivity problems appear in multiple samples: "it wouldn't connect to internet." One reviewer reported the tablet "shut off completely" within weeks. App availability is limited: "you are unable to get most apps that are offered on iTunes."

Across all Fire Tablet 7 reviews, 3.0% are negative (1–2 stars), suggesting these issues affect a meaningful minority of users.

## Weakest Product

**Fire Tablet 7 Display Wi-Fi 8 GB Includes Special Offers Magenta** ranks lowest at 4.45 / 5.0 with 3.0% negative reviews. It suffers from restricted app access, performance issues, and hardware reliability concerns. The difference between this and the top Kindle Paperwhite (4.77) is small but meaningful.

## Recommendation

Choose the **Kindle Paperwhite** for dedicated reading if you're comfortable with Amazon's ecosystem and want excellent build quality and lighting. Select the **Kindle Voyage** if budget allows and you want the best display for extensive reading. Choose **Fire HD 8** if you need multimedia capability, internet browsing, and library access. Avoid the **Fire Tablet 7** unless budget is your only constraint—consider the Paperwhite instead for better value.

================================================================================
Fire Kids Edition Tablets & Accessories
================================================================================
# Fire Kids Edition Tablets & Accessories Buying Guide

## Overview

This category includes Fire Kids Edition tablets and related accessories designed for children. The analysis covers 1,696 reviews across 2 ranked products, providing substantial evidence for comparison.

## Top Products

**Amazon Kindle Paperwhite Ebook Reader 4 GB 6 Monochrome Paperwhite Touchscreen Wi-Fi Black**
- Average rating: 4.56 stars
- Positive reviews: 92.7%
- Buyers praise its reliability for road trips and learning, with parents noting that "grandkids love it" and appreciating its suitability for young children. Multiple reviewers mentioned purchasing multiple units.

**Fire Kids Edition Tablet 7 Display Wi-Fi 16 GB Green Kid Proof Case**
- Average rating: 4.52 stars
- Positive reviews: 90.8%
- Buyers highlight the value for money, durability, and the included protective case. Parents appreciate that "the value was there with a sale price reduction" and note the "2 year no questions asked warranty replacement" as a key benefit.

The Kindle Paperwhite has a slightly higher rating (4.56 vs 4.52), but the difference is small. The Kindle Paperwhite focuses on reading, while the Fire tablet offers broader app functionality and includes a kid-proof case.

## Main Complaints

**Amazon Kindle Paperwhite:**
Of the 10 sampled low-rated reviews, common issues include:
- Hardware failures: 3 reviews mention charging problems or inability to power on
- Limited app compatibility: 2 reviews note that specific games aren't accessible and that apps require downloading before leaving WiFi
- Performance: 2 reviews cite slowness and WiFi connectivity issues
- Hardware durability: 2 reviews mention weak charging ports that wear out quickly

Across all 248 reviews, 2.4% are negative (1-2 stars).

**Fire Kids Edition Tablet:**
Of the 10 sampled low-rated reviews, main complaint themes include:
- Hardware durability: 2 reviews specifically mention charging port damage
- Hardware failures: 2 reviews report devices that won't charge or turn on
- Performance issues: 2 reviews describe slow loading and responsiveness problems
- Restricted app ecosystem: 2 reviews highlight incompatibility with Google Play Store and missing popular apps like YouTube
- Content control concerns: 1 review notes inability to block certain content

Across all 1,443 reviews, 3.6% are negative (1-2 stars).

## Weakest Product

The Fire Kids Edition Tablet 7 Display is the lowest-ranked product, with a 4.52 average rating and 3.6% negative reviews. While the difference from the Kindle Paperwhite is small, recurring complaints in sampled reviews include charging port durability issues and the restriction to Amazon's app ecosystem, which limits access to popular games.

## Recommendation

Choose the **Kindle Paperwhite** if you prioritize reading content and want a more established product with slightly better ratings. Select the **Fire Kids Edition Tablet** if you want app variety, need a 7-inch display, value the included protective case, or prefer the extended warranty coverage—though budget accordingly for potential port durability concerns.

================================================================================
Amazon Device Accessories & Chargers
================================================================================
# Amazon Device Accessories & Chargers Buying Guide

## Overview

This category contains Amazon device chargers and accessories, covering 532 total reviews across 2 ranked products. The evidence is based on 211 and 188 reviews respectively, providing solid sample sizes for comparison. Note that about 25% of reviews in this category lack clear product identification, which may affect overall category insights.

## Top Products

**Amazon 5W USB Official OEM Charger And Power Adapter For Fire Tablets And Kindle Ereaders**
- Average Rating: 4.45 stars
- Positive Reviews: 86.7%

Buyers praise this charger for quick charging speeds and compact design. Reviewers note it "charges the kindle really quickly" and highlight "good quality." Users appreciate its portability and report it charges devices faster than laptop USB ports.

**All New Kindle E Reader Black 6 Glare Free Touchscreen Display Wi-Fi Includes Special Offers**
- Average Rating: 4.43 stars
- Positive Reviews: 84.8%

This device receives slightly lower ratings than the charger. Buyers praise its convenience, with reviewers noting it allows charging "without the need of computer being on" and appreciate having charging options when traveling. However, some positive reviews mention cheaper alternatives are available elsewhere.

The difference between these products is small—only 0.02 stars separate them. Both maintain strong positive ratings above 84%.

## Main Complaints

**Amazon 5W USB Charger**
The main complaint theme is pricing, appearing in roughly 6 of the 10 sampled low-rated reviews. Buyers feel the $20 price is excessive for a basic USB adapter, with one reviewer noting "5 dollar AC to USB power adapter for 20 buck." Some buyers questioned whether a purchase was necessary at all. Additional complaints include a missing cable and lack of color options.

**Kindle E Reader**
Price complaints dominate this product too, appearing in about 7 of the 10 sampled low-rated reviews. Buyers argue the charger "should have come with the kindle" at no extra cost and feel "it should not have had to buy it." Some reviewers claim the advertising was misleading about whether a plug is included. One sample review also reported that charging performance degraded over time.

## Weakest Product

The Kindle E Reader is the weakest product with 4.43 stars and 8.1% negative reviews, compared to the charger's 4.45 stars and 10.6% negative reviews. However, the difference is minimal. Both products face similar pricing objections from dissatisfied buyers.

## Recommendation

Choose the **Amazon 5W USB Charger** if you need a dedicated, fast-charging adapter specifically optimized for Kindle devices. Select the **Kindle E Reader** if you want a complete e-reading device. Both products receive strong ratings, but buyers across both should consider third-party alternatives, as reviewers note comparable products are available at lower prices.

================================================================================
Echo & Kindle Fire Devices
================================================================================
# Echo & Kindle Fire Devices Buying Guide

## Overview

This category includes Echo and Kindle Fire devices. The analysis covers **855 total reviews** across **2 ranked products**. However, 29.9% of reviews in the category lack clear product identification, so the evidence for individual products should be considered with this limitation in mind.

## Top Products

**Fire Tablet 7 Display Wi-Fi 8 GB Includes Special Offers Magenta**
- Average rating: **4.53 stars**
- Positive reviews: **91.5%**

Buyers praise this device for being "small, light easy to read in any lighting." Users appreciate its portability and ease of use, with one reviewer noting it's "quite a bit lighter" than earlier Kindle models. It appeals to beginners and elderly users seeking a straightforward reading device. One buyer reported her 90+ year-old mother successfully uses it to read books with ease.

**Echo White**
- Average rating: **4.4 stars**
- Positive reviews: **88.1%**

This device is praised for offering "great price" and versatility. Buyers highlight its value for travel and note that "kids love it" due to abundant app storage and video capabilities. Reviewers describe it as "great little tablet once you get the hang of it."

The Fire Tablet 7 has a higher rating (4.53 vs. 4.4) and significantly better positive review percentage (91.5% vs. 88.1%), making it the stronger performer overall.

## Main Complaints

**Fire Tablet 7:**
Among the 10 sampled low-rated reviews, the most common complaint is the lack of a backlight for night reading (appearing in 4 samples). Screen brightness issues appear in 2 samples. Other complaints include the device feeling too small for comfortable reading, lacking an SD card slot, and unresponsive touch controls.

**Echo White:**
Among the 10 sampled low-rated reviews, durability problems dominate. Hardware failures appear frequently: charging port issues (3 samples), screen problems (2 samples), and devices failing within weeks of purchase. Performance complaints include the device being "slow and unresponsive" and sluggish app loading (4 samples combined). One reviewer noted difficulty removing Amazon bloatware.

Serious issues are relatively uncommon: Echo White has only 1.4% of reviews rated 1-2 stars for the Fire Tablet 7, compared to 4.7% negative reviews overall for Echo White.

## Weakest Product

**Echo White** has the lowest rating at 4.4 stars with 4.7% negative reviews. However, the difference from the Fire Tablet 7 is small. The main concern themes are hardware durability and performance sluggishness.

## Recommendation

Choose the **Fire Tablet 7** if your priority is reading books anywhere with a lightweight, intuitive device. Select **Echo White** if you want a versatile tablet for video watching, apps, and mixed media use at a budget price—though be aware of reported durability concerns in the sampled reviews.

================================================================================
Kindle Fire Tablets – 16GB
================================================================================
# Kindle Fire Tablets – 16GB Buying Guide

## Overview

This category covers Kindle Fire Tablets with 16GB storage capacity. The analysis includes 1,104 total reviews across 2 ranked products, providing substantial evidence for comparison.

## Top Products

**Brand New Amazon Kindle Fire 16 GB 7 Ips Display Tablet Wifi 16 GB Blue**
- Average Rating: 4.54 stars
- Positive Reviews: 93.1%
- 860 reviews analyzed

Buyers praise the display quality and reading experience. Reviewers highlight features like the "dim light feature and matted glass screen," and describe it as "Fast, solid, all the necessary features for an ebook." Customers appreciate the compact size, noting it "fits my small hands."

**Fire Kids Edition Tablet 7 Display Wi-Fi 16 GB Green Kid Proof Case**
- Average Rating: 4.47 stars
- Positive Reviews: 90.9%
- 241 reviews analyzed

This model performs slightly lower but remains highly rated. Buyers praise its value, with one reviewer noting they "bought 4 so far" for family members. Reviewers appreciate the memory upgrade capability and that it "works great." The kid-proof case appeals to parents purchasing for children.

The rating difference between these products is small (0.07 stars). The standard Fire tablet has more reviews and slightly higher satisfaction, while the Kids Edition offers the protective case benefit but serves a more specialized use case.

## Main Complaints

**Brand New Amazon Kindle Fire 16 GB 7 Ips Display Tablet Wifi 16 GB Blue**

Of 24 sampled low-rated reviews, main complaint themes include:
- Battery performance: 3 reviews cite poor battery life, with one stating "battery lasts a mere 15 minutes as a portable unit"
- Software/ads: 2 reviews mention "filled with ads you have to pay to remove" and app compatibility issues
- Operating system preferences: 2 reviews express disappointment the OS isn't more "android style"
- Accessory fit issues: 1 review noted protector sizing problems

Overall, only 2.8% of reviews are negative (1-2 stars), indicating serious complaints remain uncommon.

**Fire Kids Edition Tablet 7 Display Wi-Fi 16 GB Green Kid Proof Case**

Of 10 sampled low-rated reviews, main themes include:
- Device stability: 1 review reported the tablet "restarted itself over ten times"
- Audio quality: 1 review noted disappointment with sound compared to older generations
- App limitations: 2 reviews cite app update and browser limitations

Only 4.1% of reviews are negative, suggesting these issues affect a small portion of users.

## Weakest Product

The Fire Kids Edition Tablet is the lowest-ranked at 4.47 stars with 4.1% negative reviews—only marginally weaker than the standard Fire tablet's 4.54 stars and 2.8% negative rate.

## Recommendation

The **Brand New Amazon Kindle Fire 16 GB** is the stronger choice for general readers and tablet users seeking the best overall ratings and the most reviews confirming reliability.

The **Fire Kids Edition** suits parents specifically looking for a child-safe device with built-in parental controls and protective case, accepting slightly lower ratings in exchange for family-focused features.

================================================================================
Echo & Smart Home Devices
================================================================================
# Echo & Smart Home Devices Buying Guide

## Overview

This category includes Echo speakers, tablets, and Fire TV devices from Amazon. The analysis covers **12,318 reviews** across **5 products ranked**, though 46.3% of reviews in the category lack clear product identification. This buying guide focuses on the top-ranked products with sufficient review samples to identify patterns.

## Top Products

**Amazon Fire HD 10 Tablet Wi-Fi 16 GB Special Offers Silver Aluminum** leads with a **4.77 average rating** and **96.9% positive reviews** (128 total reviews). Buyers praise its ease of use, sound quality, and integration with home automation. One reviewer called it "like having a personal assistant," and another appreciated that "it doesn't take up a lot of space." This product has the highest rating in the category.

**Amazon Amazon Tap Portable Bluetooth And Wi-Fi Speaker Black** follows closely at **4.73 rating** with **95.6% positive reviews** (318 reviews). Buyers love its portability, easy setup, and Alexa integration. Reviewers highlighted that it "works with all my Amazon apps" and praised how simple the installation is. The Tap's main advantage is its built-in battery for true portability.

**Echo White** holds a **4.68 average rating** with **95.3% positive reviews** (3,569 reviews—the most-reviewed product). Owners appreciate its question-answering capability and home automation control. One buyer stated it "could not be happier with overall performance." However, with 168 reviews rated 3 stars or less, it has more total complaints than the two top products.

## Main Complaints

**Echo White** reviewers frequently mention that Alexa "doesn't have any of the answers" and struggles with non-basic queries. Multiple low-rated reviews cite the **Bing search engine limitation** compared to Google. Setup difficulty appears in several 1-2 star reviews. Sound quality is questioned by some as not justifying the price versus cheaper alternatives like the Echo Dot. Only 1.2% of all Echo White reviews are negative, indicating these are minority concerns.

**Amazon Tap** low-rated samples identify WiFi connectivity issues and confusion about the device requiring external power or battery. One reviewer expected portability without understanding battery requirements.

## Weakest Product

**Amazon Fire TV** rates **4.65**—only 0.03 points below Echo White, a negligible difference. It has **1.6% negative reviews**. Main complaints match other products: Alexa's limited search capabilities, poor understanding of complex questions, and connectivity issues appear across sampled low-rated reviews.

## Recommendation

For highest overall satisfaction, the **Fire HD 10 Tablet** offers the best rating. For portable, battery-powered use, the **Tap** excels. The **Echo White** suits buyers prioritizing home automation and accepting Alexa's current limitations with search queries.

## Generate Summeries

In [43]:
#Save the six Markdown guides
SUMMARY_DIR = REPORTS_DIR / "summaries"

SUMMARY_DIR.mkdir(
    exist_ok=True
)

for category, article in all_summaries.items():

    slug = re.sub(
        r"[^a-z0-9]+",
        "_",
        category.lower()
    ).strip("_")

    output_file = (
        SUMMARY_DIR
        / f"{slug}.md"
    )

    output_file.write_text(
        f"# {category}\n\n{article}\n",
        encoding="utf-8"
    )

print(
    f"Saved {len(all_summaries)} category guides."
)

Saved 6 category guides.

In [22]:
# Create category summary/index JSON for dashboard
summary_index = []


for category, facts in all_facts.items():

    slug = re.sub(
        r"[^a-z0-9]+",
        "_",
        category.lower()
    ).strip("_")


    summary_index.append(
        {
            "category": category,
            "reviews_in_category": facts["reviews_in_category"],
            "products_ranked": facts["products_ranked"],
            "pct_reviews_without_product_name": (
                facts["pct_reviews_without_product_name"]
            ),
            "most_reviewed_product": (
                facts["most_reviewed_product"]["name"]
                if facts["most_reviewed_product"]
                else None
            ),
            "detail_file": f"{slug}.json"
        }
    )


# --------------------------------------------------
# Save category summary
# --------------------------------------------------

CATEGORY_SUMMARY_PATH = (
    SUMMARY_DATA_DIR / "category_summary.json"
)


CATEGORY_SUMMARY_PATH.write_text(
    json.dumps(
        summary_index,
        indent=2,
        ensure_ascii=False
    ),
    encoding="utf-8"
)


print(
    f"Saved category summary to: "
    f"{CATEGORY_SUMMARY_PATH}"
)

Saved category summary to: ../reports/summaries_data/category_summary.json